### PR TITLE
Writing from a position of greater humility

### PR DESCRIPTION
**Pull request by darobin**
This PR introduces several changes that support the document in speaking from a position of greater humility. This takes several forms:

- We don't lead, we convene.
- We don't make statements that we haven't done the homework to support. The "Web's amazing success" paragraph has a number of statements that connect various things (e.g. anonymity to fraud, information sharing with misinformation) as bold statements of fact that don't seem grounded in scholarship. We should either stick to what we have a clear claim to expertise on or build atop the work of others (as opposed to relying on "well-meaning technical person common sense").
- The "We believe the WWW" part has soundbites that feel self-congratulatory, may be cheap talk that seems hard to operationalise, or are flat out dangerous (e.g. "facts over falsehood"). We shouldn't promise things that we don't know how to deliver or commit to stances that run counter to Web values.
- The vision-web section is an arbitrary subset of the EWP. If the subset is meaningful, we should ask the TAG to reflect that in its document, perhaps by giving some prominence to those four principles picked from their twelve. If it isn't, we should respect their work and not make the subset.

***
<a href="https://pr-preview.s3.amazonaws.com/darobin/AB-public/pull/134.html" title="Last updated on Oct 24, 2023, 5:30 PM UTC (0ec2943)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/AB-public/134/7a31b36...darobin:0ec2943.html" title="Last updated on Oct 24, 2023, 5:30 PM UTC (0ec2943)">Diff</a>

### CODE REVIEW

**Comment by wareid** [comment]
This revision does two polar opposite things: it removes our honest assessment of the web today, and waters down the positive goal we want to work towards. It takes the ups and downs and levels it all out to a baseline of mediocrity.

This is a vision document, how many organizations in any industry have a vision that works out to simply "we're keeping the lights on in the meeting room"?

**Comment by darobin** [comment]
I don't oppose including an honest assessment of where the web is today, nor do I oppose having positive goals. However, if the document is to provide an "honest assessment of the web today" then, well, it needs to be honest. That means it can't come across as an arbitrary laundry list and it can't be making unsubstantiated statements. Either it should acknowledge that there are unspecific problems, or it should do a reasonable job of assessing the problems. If doing a good job is too much work for this document then it should just stick to acknowledging unspecific issues.

That's why I listed this as a humility improvement. Those current parts read to me as very "engineer arrogant". The list of problems reads as someone's heavily biased personal list that happens to be elevated as the Consortium's vision and the descriptions of the issues read (again, to me) like "I don't need to read up on these issues, I'm an engineer, I just get things."

Specifically:
- The document draws causal links that I don't believe are clearly supported:
  - openness gives rise to scams, phishing, fraud — those don't exist on closed systems like app stores?
  - rapid global information sharing creates misinformation — I'm not sure I understand the purported causation?
  - "This has divided societies and incited hate." — I'm not sure what "this" refers to here, is it anonymity and rapid information sharing that have divided societies? Is there evidence for this?
- The list is weirdly partial, too — why those specific problems and not others? Are those things the three biggest problems? The three priorities that we should be tackling? I can think of quite a few problems that this doesn't list. Also, if you put yourself in the shoes of literally anyone not in the room drafting this, they're going to ask if it's because they are paying members of W3C that we don't list the unprecedented concentration of global power in the hands of a tiny number of corporations.

And same for the positive things. A statement like "facts over falsehoods" is very far from anything that I would consider to be a Web value. Why those three things? Are profits bad in a mutualist arrangement? We should either go into details and do the work that requires, or we should stick to things for which we've already done the work (a11y, privacy, etcc) and don't have to stick to statements that are either wrong or so abstract they lack clear meaning.

**Comment by wareid** [comment]
Should we also reformat the vision to be in 12 pt times new roman and double spaced? Do we prefer the citations in MLA or Chicago?

Jokes aside, this isn’t an academic paper, and these aren’t unsubstantiated claims. We don't need a list of citations for well-known issues on the web today.

I'd be happy to expand the list to include even more issues presented by the current state of the web today but this is a vision document, and as several people have pointed out, mentioning anything negative about the web as we know it is "too negative".

For the points we do support, I don't see why you take exception to these when we have work in these spaces:

We believe the World Wide Web should be inclusive and respectful of its users: [WAI, PWE, PING, i18n]
a Web that supports facts over falsehoods, [PING, DID, VC]
people over profits, [WAI, any industry activity where we work together to build interoperable standards vs. proprietary solutions]
humanity over hate. [WAI, i18n, PWE, any effort we make and continue to make to make W3C and our work more inclusive]

Can we solve all of the web's problems or society's problems and how they manifest on the web? Nope. But we never claimed we would, we are making the assertion that our goal is to do our best to consider these challenges as we operate in our scope.

I feel like I keep repeating myself but this is a vision document, if we can't be aspirational here, if we can't be optimistic or opinionated about our hopes, what is the point? It's giving pretending tech is somehow above the petty problems of humanity and we know that is categorically untrue.
________________________________

**Comment by mnot** [comment]
Robin's unspoken suggestion here might be _maybe a technical body shouldn't have a vision document._ 

Internally, a vision might be a motivating document. Externally, it can come off as oblivious to the context we're operating within, in 2023. Some people are inspired by words like those we have; others will see them as hollow statements that are used to distract.

Personally, I think that the contextualisation we're talking about over on #113 will help. However, writing anything that looks like a manifesto is going to brush up against this, and this document does read like one.

For what it's worth, this is what the IETF has:
  https://www.rfc-editor.org/rfc/rfc3935.html

**Comment by darobin** [comment]
> Robin's unspoken suggestion here might be _maybe a technical body shouldn't have a vision document_.

Either that, or it should make good on its promise and deliver an actual vision, with aspirations that aren't vacuous and a credible path to getting there.

Setting your sarcasm aside, I'm not suggesting that this should have citations but perhaps simply that it doesn't blunder into other fields with half-baked, or even wrong, claims. Putting this in perhaps starker terms, these statements are much closer to a suburban lawn sign than to a vision. I would like to suggest that we will improve the situation far more by focusing on the good we can do more than on patting ourselves on the back for meaning well in our brand new cosplay ethics outfits.

**Comment by michaelchampion** [comment]
Uhh, @drobin ....  rhetoric such as "aspirations that aren't vacuous" and " blunder into other fields with half-baked, or even wrong, claims", and  "these statements are much closer to a suburban lawn sign than to a vision" might be appropriate in the mean streets of academic or social media argumentation by put-down,  but it is against the spirit of the W3C CoC/CEPC as I understand it.

**Comment by darobin** [comment]
@michaelchampion I provided a constructive path forward which I further supported with arguments. The reaction was the chair of the group being dismissive, mocking, and sarcastic, followed by the usual closing of ranks from the AB Clique.

I'm sincerely sorry if you found my characterisation of the document offensive but I fully stand by its substance.

**Comment by cwilso** [comment]
Umm, Robin, the Chair of the TF is Tzviya, who has said nothing, and I'm the Editor, and I said nothing.  Mark, who I think you were responding to, is neither.  And only one member of the AB has responded (Wendy)?  Unless you're considering @michaelchampion part of the "AB Clique".

**Comment by darobin** [comment]
Wendy is chair of the AB. And yes, this document was produced by the AB, clearly remains an AB document, and all discussions involve a small group of current or former AB people defending the document - including putting little 👍 on each other's comments. I think that it would be helpful to acknowledge that dynamic.

**Comment by dwsinger** [comment]
Yes, that is offensive, and you knew it when you wrote it.  You're good at offense.

**Comment by darobin** [comment]
I knew that it was strong, but did not think it offensive. I would not resort even just to strong if I did not feel it impossible to get through. If someone from outside our area of expertise came out and said things like "accessibility is solved by replacing alt text with AI generated labels" or anything of the sort we would consider them to be well-intended but both wrong and arrogant. We would expect them to take the time to do some reading on the matter, and maybe stick to what they know until then.

It simply baffles me that we would then turn around and consider the same behaviour acceptable coming from us.

**Comment by TzviyaSiegman** [comment]
This thread has unacceptable communications from many people. It reflects a total lack of consensus about what the Vision should include. The AB is working on a document and opened it up to the W3C as well as the Public for commentary. I (co-chair of AB and chair of Vision TF) have come to regret this decision, because it is looking like it is IMPOSSIBLE to come to consensus about what it should include. I ask for everyone to remain civil, adhere to CEPC, and consider what you can live with in this document.  Note that a portion of this (or an earlier version) already lives on https://www.w3.org/mission/). I will close this PR if decorum is not improved.

**Comment by darobin** [comment]
I agree and I too regret becoming involved in this work. I would like to propose that that we return to the PR, which I believe is a neutral statement of the issue that can be iterated upon. I would further like to complement that with some notes which I hope are consensus-inducing:

- Ethics is about what you do, not about what you say or claim to care about. We should therefore focus on the former. 
- Missions and visions are meant to convince people that work is worth doing, that they should dedicate resources to the work. Please take a dispassionate step outside of this conversation and consider this: if you were given a choice between dedicating your limited time in this life to either A) an organisation that promises to bring peace on Earth, end world hunger, cure cancer, and bring unicorns back from extinction or B) an organisation with a narrower but more pragmatic idea of how it will effect good in the world? I know for one I would go with (B) because (A) sounds nice if you can pull it off, but highly likely to be a waste of my time. I don't want to give my time and energy to an organisation that works to put "humanity above hate" not because I don't care about humans but on the contrary because I care about humans enough that I'd like to be working on real improvements to their lives rather than abstractions about them.
- Missions and visions are also meant to ground the legitimacy of an organisation, up to and including regulatory challenge. I don't want to find myself or anyone else having to argue that browsers don't form a cartel because we value "people over profits." That… would invite a lot of pointed questions, and rightly so. What remains in the document after removing that provides a much stronger foundation.
- Finally, I strongly disagree that removing these parts produces a document that's just about "keeping the lights on." Again, aspiring to a better world is a lot more about action than about claims. It's a lot more about empowering people to do good than it is about claiming that we know what good is or what facts are. The "Operational Principles" section is the strongest section in the document (and it's possible that the title undersells it, I'm not sure how many people want to read operational principles) and on its own it grounds legitimacy and provides a path forward. If we only do the things in that section and strive to do them more and better than we currently do, we'll be building a much, _much_ better Web. The over-reaching, abstraction, and arbitrary lists that this PR proposes to remove IMHO do little other than undermine it.

**Comment by wareid** [comment]
Firstly I’d like to apologize for my joke about formatting, I meant it in jest but it was understandably not received that way and I am sorry for any offense I caused.

There is a middle ground between taking out our lofty goals and the contents of this PR. I agree our operational principles are the true “meat” of the document as it is currently written, and I wonder if we can backtrack from there.

I do think it’s valuable for us to have a vision that is aspirational in nature, that’s the point after all, to have something to strive toward. IETF’s example, as provided by Mark, is not exactly what I had in mind, and definitely has the feeling of a mission in tech circa 2004.

Most of all, I believe we all agree that we want to centre the user, people, in our vision. We make multiple mentions of humanity and users, let’s solidify that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darobin** [comment]
> Firstly I’d like to apologize for my joke about formatting, I meant it in jest but it was understandably not received that way and I am sorry for any offense I caused.

And I apologise for responding hard. It comes from my perception, perhaps erroneous, that only AB-sourced proposals are ever given consideration, but frustration is never productive and I'm sorry that I chose that path.

> There is a middle ground between taking out our lofty goals and the contents of this PR. I agree our operational principles are the true “meat” of the document as it is currently written, and I wonder if we can backtrack from there.

I absolutely agree, and the intent here is not for this to be the last PR to land before the document goes out for ratification. I think we all want, as you put it, something that doesn't have "the feeling of a mission in tech circa 2004." I'd like to suggest that we also don't want something that has the feeling of a mission in tech circa 2017. That's about the time when folks in tech started saying "first, do no harm!" or "if we have ethics, we'll avoid unintended consequences!" We owe the Web better than that.

This PR seeks to remove everything that overpromises or is arbitrary (and therefore lacks a claim to consensus), or put differently it seeks to give us a more humble foundation by shifting from what I feel reads as more personal and more hubristic towards what seems more collective and more actionable. I think that this would actually _increase_ our chances of finding a brief, impactful aspiration?

**Comment by cwilso** [comment]
I am locking this thread, as the commentary got out of hand.  I appreciate the last few comments, but I’d like to hit refresh. There has been some less-than-optimal tone all around. I would particularly like to ask that we be respectful of everyone’s viewpoint; pointing out a need to solidify support and make work actionable is productive, referring to a consensus work document as vacuous and half-baked is not.

Additionally, as editor of this document I am closing this PR without prejudice. I gave directive guidance to the AC on how to participate in the Vision work at the AC meeting this spring (in https://www.w3.org/2023/Talks/ac-slides/vision/):

- Take the time to be concise and impactful.
- Please file separate issues for separate things
- Please file issues to build consensus before building big PRs
- Make proposals! “I think we should add X to our list of goals”
- Participate in discussion in Github and in meetings.

At this point, we are working in a consensus manner, and we should work on building consensus for substantial reworks, and not file large PRs unless they are necessarily related issues. Filing a PR with half a dozen substantial changes, particularly removing sections that have gained explicit consensus in the TF without any discussion in the TF, is not productive; filing separate PRs with relevant issues explained will hopefully at least engender discussion.

**Pull request closed without merging**
