### PR TITLE
Break up a complicated bullet

### PR DESCRIPTION
**Pull request by mnot**
There is a _lot_ packed into this bullet point; this is one way to make it more digestable.

### CODE REVIEW

**Comment by cwilso** [comment]
#30 already breaks this bullet up, into different thoughts that are more related.  Also, there is an additional bullet added by this PR around collective empowerment; that really needs to be broken out into a issue for discussion, and a separate PR.  (Off the cuff, I'm unclear what this is adding over the collective empowerment principle and the clear "inclusion, fairness, consensus, equity" thread running through the entire document, but I'm certainly open.)

**Comment by mnot** [comment]
Fair enough. 'Collective empowerment' wasn't an addition; just moving it from inside the bullet.

**Comment by cwilso** [comment]
Ah, got it.  Was confused by where it moved.  Yep, that point is there in #30 - PTAL.

**Comment by cwilso** [comment]
Since this has been broken up, closing this PR.

**Pull request closed without merging**
