### PR TITLE
Rename Introduction to Background

### PR DESCRIPTION
**Pull request by fantasai**
This section is really about historical and contextual background; the actual “introduction” to the document is the previous section.

***
<a href="https://pr-preview.s3.amazonaws.com/fantasai/AB-public/pull/183.html" title="Last updated on Oct 8, 2024, 3:10 AM UTC (f3ccfea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/AB-public/183/2d5fcbf...fantasai:f3ccfea.html" title="Last updated on Oct 8, 2024, 3:10 AM UTC (f3ccfea)">Diff</a>

### CODE REVIEW

**Comment by cwilso** [comment]
I don't think this should be done unless we rename Purpose "Introduction" and give matching anchor names to the sections.

**Comment by fantasai** [comment]
@cwilso I'm OK with that direction; was debating whether to do it and went with the minimal change option. Would you like me to update the PR?

**Comment by celestaria** [comment]
@cwilso What about we add a separate Purpose "Introduction" at line 59 where the document talks about the web?

**Comment by celestaria** [comment]
@cwilso @fantasai And we add (WWW) in parentheses to line 47?

**Review by tantek — CHANGES_REQUESTED** [review]
I'd rather keep "Introduction" as section header, similar to the Ethical Web Principles.

I don't think this is an improvement, and I'd rather not open the door for wordsmithing for an updated Note. 

I'd prefer to **close this PR with no changes**, and discourage wordsmithing (would prefer spending time on helping process the remaining [outstanding open Vision project issues](https://github.com/w3c/AB-public/issues?q=is%3Aissue+is%3Aopen+label%3A%22Project+Vision%22+-label%3ADefer) instead, as well as those expected from upcoming explicit wide review and horizontal reviews.)

**Comment by frivoal** [comment]
I would support the combined rename suggested by @fantasai and @cwilso, but I can also live without doing it.

**Comment by wareid** [comment]
I agree with Tantek, I would prefer to leave this as is.

**Comment by fantasai** [comment]
@tantek I think the [Introduction to the Ethical Web Principles](https://www.w3.org/TR/ethical-web-principles/) is in fact an introduction to the rest of the document; but the current "Introduction" for the Vision explains historical background and context, but doesn't really _introduce_ the rest of the document. That's my issue here, and why I proposed the renaming.

**Comment by cwilso** [comment]
After reflecting on this further: I don't think it is right to rename the current "Introduction" as "Background".  It *is*, in fact, an introduction to the document; why the concept exists, why we think it's important (it does put it in an historical context, but so does the EWP's introduction) and what the document does.

HOWEVER:
I do think a positive change that helps the issue @fantasai is calling out could be made by taking the current "purpose" section, and 

1) using the first paragraph of current purpose section up in place of the abstract (they say nearly the same thing), and 
2) moving the Goals list from the current purpose to the end of the introduction, which tightens up its utility as an introduction.

I'll toss together a PR if this sounds like it would be an improvement.  Other than that, though, I have to agree, I would still weigh in on "no change".

**Comment by tantek** [comment]
I'm seeing rough consensus here for "no change" so I'm closing accordingly, especially as this PR (and issues mentioned therein) is unnecessary for an updated Note.

In addition, wordsmithing is not essential for publishing an updated Note, please defer any such suggestions, because they will almost certainly be moot in the context of feedback we get from wide review.

**Pull request closed without merging**
