### PR TITLE
Fix #32: Don't refer to people as "other things"

### LINKED ISSUE #32: Don't refer to people as "other things"
Per PR #21, we should remove the "etc." from the bullet point

* Increase involvement of under-represented key stakeholders such as end users, content creators, developers etc.

(I'll do this once #30 lands.)

### PR DESCRIPTION
**Pull request by cwilso**

### CODE REVIEW

**Review by tantek — CHANGES_REQUESTED** [review]
Please keep the Oxford comma. e.g.:
"end users, content creators, and developers."
With that, LGTM.

**Comment by cwilso** [comment]
SIIIIIIIIIIGH.  I just looked around in the doc and followed what I thought was the "standard".  (the other bullets in this particular list do not have Oxford commas.)  Unfortunately we appear to currently have an equal number of Oxford commas and lack of Oxford commas, so I filed https://github.com/w3c/AB-public/issues/39.  Please vote there and I'll just enforce a style.  I don't personally care, but I'd like to not block this commit on this style issue; it will get fixed up either way.

**Review by tantek — COMMENTED** [review]
Can we please close this one with leaving its Oxford comma as is and then separately debate the larger issue? No need to introduce that as a dependency to resolve this issue as originally stated. Thanks

**Comment by cwilso** [comment]
If you want to make a commit to this PR, go for it.  Otherwise, your concern is valid and noted, but the issue is bigger than you had called out.  (I only removed the comma to match the style of the lines both immediately above and immediately below, so as it is, this is measurably more in tune with the surrounding text.)  Either way, the issue will be fixed (one way or the other) in a week.  If you insist this must not be checked in as-is (despite it being clearly something that 1) isn't definitively wrong, and 2) will be fixed or the surrounding content will in the very near future, then I'm simply going to leave this PR open until #39 has resolved and I get back to this.  Or close this PR without comment, and perhaps I'll get to #32 some time in the future if no one else does in the meantime.

**Pull request merged**
