### PR TITLE
PR in preparation of Nov 30 AB meeting

### PR DESCRIPTION
**Pull request by avneeshsingh**
This is the pull request for discussion in Nov 30 AB meeting. I will explain the proposed reorganization in the meeting.

### CODE REVIEW

**Comment by cwilso** [comment]
For the benefit of those not on the AB, but still participating here, it might be good to write that explanation here too.

**Comment by chrisn** [comment]
I'd like also to suggest that the AB also consider how to involve other folks interested in this, who aren't necessarily AB members themselves.

**Comment by cwilso** [comment]
@chrisn You're here.  :P  Seriously, though, this is why we have the document and the issues here in AB-public, to encourage others to participate.  We try to have the bulk of our work happen asynchronously; if synchronous meetings were turning in to a large part of the work and non-AB members were participating in the discussion, I imagine the AB chairs would ask to include them in those discussions.

**Comment by chrisn** [comment]
Thanks, that approach sounds good to me.

**Comment by michaelchampion** [comment]
I strongly urge @avneeshsingh to withdraw this PR or the AB to reject it.
- It is a large set of changes to a document that has been collaboratively developed for some years now
- The changes don't have explanations as to what problems in the previous draft they are intended to solve
- I believe it un-does changes / removes text that had rough consensus

**Comment by TzviyaSiegman** [comment]
This will be transitioned to issues

**Comment by TzviyaSiegman** [comment]
@avneeshsingh will create Issues

**Pull request closed without merging**
