### PR TITLE
Interop restructure

### LINKED ISSUE #120: Multiple implementations point
Per @fantasai comment:

We technically don't require multiple implementations or open test suites (though it's definitely recommended and what most groups do)... I also want to try to make this more of an active point than a "we believe" point, maybe something like

We solicit multiple implementations and develop open test suites in order to ensure interoperability and fitness for purpose and facilitate the broad adoption of our standards.

(I don't actually like this sentence much, but just wanted to get an idea across as something to play with.)

### PR DESCRIPTION
**Pull request by cwilso**
Fixes #120

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/AB-public/pull/152.html" title="Last updated on Jan 30, 2024, 6:35 PM UTC (c5e9026)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/AB-public/152/ff3e260...c5e9026.html" title="Last updated on Jan 30, 2024, 6:35 PM UTC (c5e9026)">Diff</a>

### CODE REVIEW

**Comment by cwilso** [comment]
This replaces PR #136

**Review by tantek — CHANGES_REQUESTED** [review]
Looks good except I'd make one line slightly stronger:

s/enable independent interoperable implementations/enable & encourage independent interoperable implementations

**Review by frivoal — APPROVED** [review]

**Review by fantasai — APPROVED** [review]
Mild preference for keeping `multiple`, since it emphasizes that point more than just having the plural; but also this works and I'm sympathetic to the "fewer words is better" argument. :)

**Review by tantek — APPROVED** [review]
this is an improvement. consider the suggestion for "& encourage" optional or something stronger like "require"

**Pull request merged**
